import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuthenticator } from '@aws-amplify/ui-react'
import { fetchAuthSession } from 'aws-amplify/auth'
import { API_URL } from '../aws-exports'

const STEPS = ['Personal Info', 'Fitness Goals', 'Event Training', 'Lifestyle', 'Equipment']

const GOALS = ['Build Muscle', 'Build Strength', 'Build Cardiovascular Health', 'Mobility', 'Lose Weight', 'Event']
const GYM_EXPERIENCE = ['0 years', '1-2 years', '2-4 years', '5+ years']
const FITNESS_RANKS = ['Beginner', 'Intermediate', 'Pro', 'Expert']
const JOB_DEMANDS = ['Low', 'Moderate', 'High']
const ENVIRONMENTS = ['Bodyweight Only', 'Home Gym', 'Full Commercial Gym']
const HOME_EQUIPMENT = [
  'Dumbbells', 'Barbells + Plates', 'Resistance Bands', 'Kettlebells',
  'Bench', 'Squat Rack', 'Smith Machine', 'Cable Machine',
  'Leg Press Machine', 'Pull Up Bar', 'Dip Bars', 'Adjustable Bench', 'Other'
]

const initialForm = {
  first_name: '', last_name: '', gender: '', age: '', weight: '', weight_unit: 'kg', height: '', height_unit: 'ft',
  goals: [], fitness_experience: '', fitness_rank: '',
  event_training: false, event_name: 'N/A', event_customization: false,
  work_hours: '', workout_duration: '', job_difficulty: '', injuries: 'None',
  environment: '', home_gym_equipment: [],
}

export default function Questionnaire() {
  const [step, setStep] = useState(0)
  const [form, setForm] = useState(initialForm)
  const [loading, setLoading] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [error, setError] = useState('')
  const { user, signOut } = useAuthenticator((context) => [context.user])
  const navigate = useNavigate()

  const updateField = (field, value) => setForm(prev => ({ ...prev, [field]: value }))

  const isStepValid = () => {
    switch (step) {
      case 0: {
        const w = parseFloat(form.weight)
        const h = parseFloat(form.height)
        const validWeight = form.weight_unit === 'kg' ? w >= 20 && w <= 300 : w >= 44 && w <= 660
        const validHeight = form.height_unit === 'cm' ? h >= 50 && h <= 280 : h >= 1 && h <= 9
        return !!(form.first_name && form.last_name && form.gender && form.age && validWeight && validHeight)
      }
      case 1:
        return form.goals.length > 0 && !!(form.fitness_experience && form.fitness_rank)
      case 2:
        if (form.event_training) return !!(form.event_name && form.event_name !== 'N/A')
        return true
      case 3:
        return !!(form.work_hours && form.workout_duration && form.job_difficulty)
      case 4:
        if (form.environment === 'Home Gym') return form.home_gym_equipment.length > 0
        return !!form.environment
      default:
        return true
    }
  }

  const toggleArrayItem = (field, value) => {
    setForm(prev => ({
      ...prev,
      [field]: prev[field].includes(value)
        ? prev[field].filter(i => i !== value)
        : [...prev[field], value]
    }))
  }

  const handleSubmit = async () => {
    setLoading(true)
    setError('')
    try {
      const session = await fetchAuthSession()
      const token = session.tokens.idToken.toString()

      const payload = {
        ...form,
        age: parseInt(form.age),
        weight: parseInt(form.weight),
        height: parseFloat(form.height),
        work_hours: parseInt(form.work_hours),
        workout_duration: parseInt(form.workout_duration),
      }

      const res = await fetch(`${API_URL}/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': token,
        },
        body: JSON.stringify(payload),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || 'Something went wrong')
      }

      setSubmitted(true)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  if (submitted) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center px-4">
        <div className="text-center max-w-md">
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-gradient-to-br from-cyan-500 to-cyan-400 mb-6 shadow-lg shadow-cyan-500/30">
            <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <h2 className="text-3xl font-bold text-white mb-3">Plan In Progress!</h2>
          <p className="text-gray-400 mb-2">
            Your personalized workout plan is being generated by AI.
          </p>
          <p className="text-gray-400 mb-8">
            You'll receive an email at <span className="text-cyan-400">{user?.signInDetails?.loginId}</span> when it's ready.
          </p>
          <button
            onClick={() => navigate('/workout')}
            className="px-6 py-3 bg-gradient-to-r from-cyan-500 to-cyan-400 text-white font-semibold rounded-xl hover:opacity-90 transition-opacity"
          >
            Check My Plan
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] px-4 py-8 relative overflow-hidden">

      {/* Background dumbbell decorations */}
      <svg className="absolute -top-10 -left-16 w-96 h-96 text-cyan-500 opacity-[0.04] rotate-[-30deg] pointer-events-none" viewBox="0 0 120 48" fill="currentColor">
        <rect x="0" y="12" width="20" height="24" rx="4"/>
        <rect x="8" y="16" width="10" height="16" rx="2"/>
        <rect x="18" y="20" width="84" height="8" rx="3"/>
        <rect x="102" y="16" width="10" height="16" rx="2"/>
        <rect x="100" y="12" width="20" height="24" rx="4"/>
      </svg>
      <svg className="absolute top-1/3 -right-20 w-[500px] h-[500px] text-cyan-400 opacity-[0.04] rotate-[20deg] pointer-events-none" viewBox="0 0 120 48" fill="currentColor">
        <rect x="0" y="12" width="20" height="24" rx="4"/>
        <rect x="8" y="16" width="10" height="16" rx="2"/>
        <rect x="18" y="20" width="84" height="8" rx="3"/>
        <rect x="102" y="16" width="10" height="16" rx="2"/>
        <rect x="100" y="12" width="20" height="24" rx="4"/>
      </svg>
      <svg className="absolute -bottom-10 left-1/4 w-80 h-80 text-cyan-500 opacity-[0.04] rotate-[10deg] pointer-events-none" viewBox="0 0 120 48" fill="currentColor">
        <rect x="0" y="12" width="20" height="24" rx="4"/>
        <rect x="8" y="16" width="10" height="16" rx="2"/>
        <rect x="18" y="20" width="84" height="8" rx="3"/>
        <rect x="102" y="16" width="10" height="16" rx="2"/>
        <rect x="100" y="12" width="20" height="24" rx="4"/>
      </svg>

      {/* Subtle cyan glow orbs */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-cyan-500/5 rounded-full blur-3xl pointer-events-none"/>
      <div className="absolute bottom-0 right-0 w-[400px] h-[400px] bg-cyan-400/5 rounded-full blur-3xl pointer-events-none"/>

      <div className="max-w-2xl mx-auto relative z-10">

        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <button onClick={() => navigate('/')} className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-cyan-500 to-cyan-400 flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <span className="text-white font-bold text-lg">PeakCore AI</span>
          </button>
          <button onClick={() => { signOut(); navigate('/login') }} className="text-gray-500 hover:text-gray-300 text-sm transition-colors">
            Sign out
          </button>
        </div>

        {/* Progress bar */}
        <div className="mb-8">
          <div className="flex justify-between mb-2">
            {STEPS.map((s, i) => (
              <span key={s} className={`text-xs font-medium hidden sm:block ${i <= step ? 'text-cyan-500' : 'text-gray-600'}`}>
                {s}
              </span>
            ))}
          </div>
          <div className="h-1.5 bg-[#2a2a2a] rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-cyan-500 to-cyan-400 rounded-full transition-all duration-500"
              style={{ width: `${((step + 1) / STEPS.length) * 100}%` }}
            />
          </div>
          <p className="text-gray-500 text-xs mt-2">Step {step + 1} of {STEPS.length}: {STEPS[step]}</p>
        </div>

        {/* Card */}
        <div className="bg-[#141414] border border-[#1e1e1e] rounded-2xl p-6 sm:p-8">
          <h2 className="text-xl font-bold text-white mb-6">{STEPS[step]}</h2>

          {/* Step 1 — Personal Info */}
          {step === 0 && (
            <div className="space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <Field label="First Name">
                  <input type="text" value={form.first_name} onChange={e => updateField('first_name', e.target.value)}
                    placeholder="Daniel" className={inputClass} />
                </Field>
                <Field label="Last Name">
                  <input type="text" value={form.last_name} onChange={e => updateField('last_name', e.target.value)}
                    placeholder="Nguyen" className={inputClass} />
                </Field>
              </div>
              <Field label="Gender">
                <div className="grid grid-cols-2 gap-3">
                  {['Male', 'Female'].map(g => (
                    <OptionButton key={g} selected={form.gender === g} onClick={() => updateField('gender', g)}>
                      {g}
                    </OptionButton>
                  ))}
                </div>
              </Field>
              <div className="grid grid-cols-3 gap-4">
                <Field label="Age">
                  <input type="number" value={form.age} onChange={e => updateField('age', e.target.value)}
                    placeholder="25" className={inputClass} min="13" max="100" />
                </Field>
                <Field label={`Weight (${form.weight_unit === 'kg' ? '20–300 kg' : '44–660 lb'})`}>
                  <div className="flex gap-2">
                    <input type="number" value={form.weight} onChange={e => updateField('weight', e.target.value)}
                      placeholder={form.weight_unit === 'kg' ? '80' : '176'}
                      min={form.weight_unit === 'kg' ? 20 : 44}
                      max={form.weight_unit === 'kg' ? 300 : 660}
                      className={`${inputClass} flex-1`} />
                    <select value={form.weight_unit} onChange={e => { updateField('weight_unit', e.target.value); updateField('weight', '') }}
                      className="bg-[#0a0a0a] border border-[#1e1e1e] text-gray-300 rounded-xl px-2 text-sm focus:border-cyan-500 focus:outline-none">
                      <option value="kg">kg</option>
                      <option value="lb">lb</option>
                    </select>
                  </div>
                </Field>
                <Field label={`Height (${form.height_unit === 'cm' ? '50–280 cm' : '1–9 ft'})`}>
                  <div className="flex gap-2">
                    <input type="number" value={form.height} onChange={e => updateField('height', e.target.value)}
                      placeholder={form.height_unit === 'cm' ? '180' : '6'}
                      min={form.height_unit === 'cm' ? 50 : 1}
                      max={form.height_unit === 'cm' ? 280 : 9}
                      className={`${inputClass} flex-1`} />
                    <select value={form.height_unit} onChange={e => { updateField('height_unit', e.target.value); updateField('height', '') }}
                      className="bg-[#0a0a0a] border border-[#1e1e1e] text-gray-300 rounded-xl px-2 text-sm focus:border-cyan-500 focus:outline-none">
                      <option value="cm">cm</option>
                      <option value="ft">ft</option>
                    </select>
                  </div>
                </Field>
              </div>
            </div>
          )}

          {/* Step 2 — Fitness Goals */}
          {step === 1 && (
            <div className="space-y-6">
              <Field label="What are your workout goals? (select all that apply)">
                <div className="grid grid-cols-2 gap-2">
                  {GOALS.map(g => (
                    <ToggleButton key={g} selected={form.goals.includes(g)} onClick={() => toggleArrayItem('goals', g)}>
                      {g}
                    </ToggleButton>
                  ))}
                </div>
              </Field>
              <Field label="How long have you been going to the gym?">
                <div className="grid grid-cols-2 gap-2">
                  {GYM_EXPERIENCE.map(e => (
                    <OptionButton key={e} selected={form.fitness_experience === e} onClick={() => updateField('fitness_experience', e)}>
                      {e}
                    </OptionButton>
                  ))}
                </div>
              </Field>
              <Field label="Experience level">
                <div className="grid grid-cols-2 gap-2">
                  {FITNESS_RANKS.map(r => (
                    <OptionButton key={r} selected={form.fitness_rank === r} onClick={() => updateField('fitness_rank', r)}>
                      {r}
                    </OptionButton>
                  ))}
                </div>
              </Field>
            </div>
          )}

          {/* Step 3 — Event Training */}
          {step === 2 && (
            <div className="space-y-5">
              <Field label="Are you training for a specific event?">
                <div className="grid grid-cols-2 gap-3">
                  <OptionButton selected={form.event_training === true} onClick={() => updateField('event_training', true)}>
                    Yes
                  </OptionButton>
                  <OptionButton selected={form.event_training === false} onClick={() => {
                    updateField('event_training', false)
                    updateField('event_name', 'N/A')
                    updateField('event_customization', false)
                  }}>
                    No
                  </OptionButton>
                </div>
              </Field>

              {form.event_training && (
                <>
                  <Field label="What event are you training for?">
                    <input type="text" value={form.event_name === 'N/A' ? '' : form.event_name}
                      onChange={e => updateField('event_name', e.target.value || 'N/A')}
                      placeholder="e.g. Marathon, Powerlifting Meet, Spartan Race"
                      className={inputClass} />
                  </Field>
                  <Field label="Do you want a workout plan specifically for this event?">
                    <div className="grid grid-cols-2 gap-3">
                      <OptionButton selected={form.event_customization === true} onClick={() => updateField('event_customization', true)}>
                        Yes
                      </OptionButton>
                      <OptionButton selected={form.event_customization === false} onClick={() => updateField('event_customization', false)}>
                        No
                      </OptionButton>
                    </div>
                  </Field>
                </>
              )}

              {!form.event_training && (
                <div className="bg-[#0a0a0a] border border-[#1e1e1e] rounded-xl p-4">
                  <p className="text-gray-500 text-sm text-center">
                    No event training selected. Your plan will focus on your fitness goals.
                  </p>
                </div>
              )}
            </div>
          )}

          {/* Step 4 — Lifestyle */}
          {step === 3 && (
            <div className="space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <Field label="Hours worked per week">
                  <input type="number" value={form.work_hours} onChange={e => updateField('work_hours', e.target.value)}
                    placeholder="40" className={inputClass} min="0" max="100" />
                </Field>
                <Field label="Session duration (minutes)">
                  <input type="number" value={form.workout_duration} onChange={e => updateField('workout_duration', e.target.value)}
                    placeholder="60" className={inputClass} min="15" max="180" />
                </Field>
              </div>
              <Field label="How demanding is your job?">
                <div className="grid grid-cols-3 gap-2">
                  {JOB_DEMANDS.map(d => (
                    <OptionButton key={d} selected={form.job_difficulty === d} onClick={() => updateField('job_difficulty', d)}>
                      {d}
                    </OptionButton>
                  ))}
                </div>
              </Field>
              <Field label="Do you have any injuries or limitations?">
                <textarea
                  value={form.injuries === 'None' ? '' : form.injuries}
                  onChange={e => updateField('injuries', e.target.value || 'None')}
                  placeholder="e.g. Lower back pain, bad knees. Leave blank if none."
                  rows={3}
                  className={`${inputClass} resize-none`}
                />
              </Field>
            </div>
          )}

          {/* Step 5 — Equipment */}
          {step === 4 && (
            <div className="space-y-6">
              <Field label="Where do you plan to work out?">
                <div className="space-y-2">
                  {ENVIRONMENTS.map(e => (
                    <OptionButton key={e} selected={form.environment === e} onClick={() => {
                      updateField('environment', e)
                      if (e !== 'Home Gym') updateField('home_gym_equipment', [])
                    }}>
                      {e}
                    </OptionButton>
                  ))}
                </div>
              </Field>

              {form.environment === 'Home Gym' && (
                <Field label="What equipment do you have? (select all that apply)">
                  <div className="grid grid-cols-2 gap-2">
                    {HOME_EQUIPMENT.map(eq => (
                      <ToggleButton key={eq} selected={form.home_gym_equipment.includes(eq)}
                        onClick={() => toggleArrayItem('home_gym_equipment', eq)}>
                        {eq}
                      </ToggleButton>
                    ))}
                  </div>
                </Field>
              )}
            </div>
          )}

          {/* Error */}
          {error && (
            <div className="mt-4 p-3 bg-cyan-400/10 border border-cyan-400/20 rounded-xl">
              <p className="text-cyan-300 text-sm">{error}</p>
            </div>
          )}

          {/* Navigation */}
          <div className="flex justify-between mt-8 gap-3">
            {step > 0 ? (
              <button onClick={() => setStep(s => s - 1)}
                className="px-5 py-2.5 border border-[#1e1e1e] text-gray-400 rounded-xl hover:border-gray-500 hover:text-gray-300 transition-all text-sm font-medium">
                Back
              </button>
            ) : <div />}

            {step < STEPS.length - 1 ? (
              <button onClick={() => setStep(s => s + 1)} disabled={!isStepValid()}
                className="px-6 py-2.5 bg-gradient-to-r from-cyan-500 to-cyan-400 text-white rounded-xl hover:opacity-90 transition-opacity text-sm font-semibold shadow-lg shadow-cyan-500/20 disabled:opacity-40 disabled:cursor-not-allowed">
                Continue
              </button>
            ) : (
              <button onClick={handleSubmit} disabled={loading}
                className="px-6 py-2.5 bg-gradient-to-r from-cyan-500 to-cyan-400 text-white rounded-xl hover:opacity-90 transition-opacity text-sm font-semibold shadow-lg shadow-cyan-500/20 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2">
                {loading && (
                  <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                )}
                {loading ? 'Submitting...' : 'Generate My Plan'}
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

// Reusable components

const inputClass = "w-full bg-[#0a0a0a] border border-[#1e1e1e] text-white rounded-xl px-4 py-2.5 text-sm focus:border-cyan-500 focus:outline-none placeholder-gray-600 transition-colors"

function Field({ label, children }) {
  return (
    <div>
      <label className="block text-gray-400 text-xs font-medium uppercase tracking-wider mb-2">{label}</label>
      {children}
    </div>
  )
}

function OptionButton({ selected, onClick, children }) {
  return (
    <button onClick={onClick}
      className={`w-full py-2.5 px-4 rounded-xl text-sm font-medium border transition-all ${
        selected
          ? 'bg-gradient-to-r from-cyan-500/20 to-cyan-400/20 border-cyan-500 text-cyan-400'
          : 'bg-[#0a0a0a] border-[#1e1e1e] text-gray-400 hover:border-gray-500 hover:text-gray-300'
      }`}>
      {children}
    </button>
  )
}

function ToggleButton({ selected, onClick, children }) {
  return (
    <button onClick={onClick}
      className={`py-2.5 px-4 rounded-xl text-sm font-medium border transition-all flex items-center gap-2 ${
        selected
          ? 'bg-cyan-500/10 border-cyan-500 text-cyan-400'
          : 'bg-[#0a0a0a] border-[#1e1e1e] text-gray-400 hover:border-gray-500'
      }`}>
      <span className={`w-3.5 h-3.5 rounded flex-shrink-0 flex items-center justify-center border ${
        selected ? 'bg-cyan-500 border-cyan-500' : 'border-gray-600'
      }`}>
        {selected && (
          <svg className="w-2.5 h-2.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
          </svg>
        )}
      </span>
      {children}
    </button>
  )
}
